# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Influo < Formula
  desc "TUI client for agent.influo-ai.com — chat with brand agents from your terminal"
  homepage "https://github.com/yomomo-ai/homebrew-tap"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.17/influo_darwin_amd64.tar.gz"
      sha256 "afde38675d47b11b151428a593b61b797afbd33fb98a56986f7bac989e2e31cf"

      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.17/influo_darwin_arm64.tar.gz"
      sha256 "330aa29b09cf11fcba7a570288dc458bcb757454e4e5db3aba248f846c9dd4c2"

      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.17/influo_linux_amd64.tar.gz"
      sha256 "d2725989abfc339d823828c08e1c2403a10fc8c75351f98c25092ecb6cafd8ed"
      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.17/influo_linux_arm64.tar.gz"
      sha256 "0699ee3354ef3f9e5b5c6c3e3fa3121bb03a0ed0ac3c6755fc1ac36c98d064f0"
      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  test do
    assert_match "influo", shell_output("#{bin}/influo --version", 0).strip
  end
end
