# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Influo < Formula
  desc "TUI client for agent.influo-ai.com — chat with brand agents from your terminal"
  homepage "https://github.com/yomomo-ai/homebrew-tap"
  version "0.1.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.18/influo_darwin_amd64.tar.gz"
      sha256 "e7957d24fa12e20cbaebaff0e5f013eb63a9b5d94f5ddb305e89f79543666257"

      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.18/influo_darwin_arm64.tar.gz"
      sha256 "03d3abbb1e0d2a80b2c55fe258ba1ad56874f6a4424f40ef818a4848120eb807"

      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.18/influo_linux_amd64.tar.gz"
      sha256 "5801ed8b6b98eb1a624d2831da6df56dccbee33df0edd2e985030a421ca62945"
      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.18/influo_linux_arm64.tar.gz"
      sha256 "250600b1d183ffeb1ade237d3b7b29bcb5cbb80be73fc3a6193140aff318a15f"
      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  test do
    assert_match "influo", shell_output("#{bin}/influo --version", 0).strip
  end
end
