# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Influo < Formula
  desc "TUI client for agent.influo-ai.com — chat with brand agents from your terminal"
  homepage "https://github.com/yomomo-ai/homebrew-tap"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.20/influo_darwin_amd64.tar.gz"
      sha256 "e8894d997a1d48045b3b34d9975b1a1a63989fdbd4a03b224184bc822c8b17d3"

      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.20/influo_darwin_arm64.tar.gz"
      sha256 "0ac66c9ed7bd0cdee0a27fc2cd47a588c332989149eb0ea3a48a4ac0cee3fddf"

      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.20/influo_linux_amd64.tar.gz"
      sha256 "90f3637c71bf63d53309e4177659d4e7b6dabd2e287885a04f4ace890f5291cb"
      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.20/influo_linux_arm64.tar.gz"
      sha256 "7dbdc0d6170f6e227ec3c68d42eb20a912c7e4d4de2a15c9c853e082ef4515bf"
      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  test do
    assert_match "influo", shell_output("#{bin}/influo --version", 0).strip
  end
end
