# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Influo < Formula
  desc "TUI client for agent.influo-ai.com — chat with brand agents from your terminal"
  homepage "https://github.com/yomomo-ai/homebrew-tap"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.19/influo_darwin_amd64.tar.gz"
      sha256 "9eabb9ec744fc7011d8127e482d9110ce6715bd68b142acb2c1d58800987deb1"

      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.19/influo_darwin_arm64.tar.gz"
      sha256 "5b80ada5de8bfc821d31b4066bc9684b08882c0c76ea8a98bde4fefedc149f4e"

      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.19/influo_linux_amd64.tar.gz"
      sha256 "f32a8d2bf3574bbf2abc0ddd38e1f631036c4afa069dc95e30eb7ad49b598f13"
      define_method(:install) do
        bin.install "influo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yomomo-ai/homebrew-tap/releases/download/v0.1.19/influo_linux_arm64.tar.gz"
      sha256 "372633db1bc735f22f4b10a782b67fe7e9ce514d87fd12dcce050b938e2bbc92"
      define_method(:install) do
        bin.install "influo"
      end
    end
  end

  test do
    assert_match "influo", shell_output("#{bin}/influo --version", 0).strip
  end
end
